# Generated by Django 2.2.11 on 2020-03-31 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='descritpion',
            new_name='description',
        ),
    ]
